;;; debase-gen.el --- Generate D-Bus bindings        -*- lexical-binding: t; -*-

;; Copyright (C) 2020  Ian Eure

;; Author: Ian Eure <ian@retrospec.tv>
;; Keywords: extensions

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; debase-gen generates bindings for D-Bus interfaces.

;;; Code:

(defun debase--services (bus)
  "Return a list of all D-Bus services on BUS."
  (cl-remove-if (lambda (service-name) (= ?: (elt service-name 0)))
                (dbus-call-method bus "org.freedesktop.DBus" "/" "org.freedesktop.DBus" "ListNames")))

(defun debase--paths (bus service &optional path)
  "Return a list of all child objects of PATH paths within SERVICE on BUS."
  (or (cl-loop for child in (dbus-introspect-get-node-names bus service (or path "/"))
               append (debase--paths bus service (concat (or path "") "/" child)))
      (list path)))

(defun debase--interfaces (bus service path)
  "Return a list of all interfaces supported by D-Bus object at PATH, in SERVICE, on BUS."
  (dbus-introspect-get-interface-names bus service path))

(defun debase--interfaces-defs (bus service path)
  "Return a list of all interfaces supported by D-Bus object at PATH, in SERVICE, on BUS."
  (debase--object-interfaces (dbus-introspect-xml bus service path) :all))

(defun debase--all-interfaces (bus)
  "Return information about all interfaces on BUS."

  (cl-loop for service in (-take 2 (debase--services bus))
           with interfaces = nil
           do (cl-loop for path in (-take 2 (debase--paths bus service))
                       do (cl-loop for interface in (debase--interfaces bus service path)
                                   do (push (list interface bus service path) interfaces)))
           finally return interfaces))

(defun debase--complete-bus ()
  (intern (completing-read "Bus: " '(":system" ":session") nil t ":system")))

(defun debase--complete-service (bus)
  (completing-read "Service: " (debase--services bus) nil t))

(defun debase--complete-path (bus service)
  (completing-read "Path: " (debase--paths bus service) nil t))

(defun debase--complete-interface (bus service path)
  (completing-read "Interface: " (debase--interfaces bus service path) nil t))

(defun debase--complete ()
  "Complete a bus, service, object, and interface."
  (interactive)
  (let* ((case-fold-search nil)
         (bus (debase--complete-bus))
         (service (debase--complete-service bus))
         (path (debase--complete-path bus service))
         (interface (debase--complete-interface bus service path)))
    (list bus service path interface)))

(defun debase--generate (class-name file-name feature-name interface-xml)
  "Generate class CLASS-NAME for a D-Bus interface INTERFACE-XML."
  (with-output-to-string
    (princ (format ";;; %s --- D-Bus bindings -*- lexical-binding: t; -*-

;; Copyright (C) %s Ian Eure

;; Author: %s <%s>
;; Keywords: extensions

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This file contains autogenerated bindings for the %s D-Bus interface.
;;
;; Do not edit this file!  Extend the classes or override their methods.

;;; Code:

" file-name 2020 user-full-name
user-full-name user-mail-address (debase-interface-name interface-xml)))

    (mapc (lambda (elt)
            (pp elt)
            (princ "\n"))
          (debase-interface->class*
           (make-symbol class-name)
           interface-xml
           :prefix (concat class-name "-")))

    (princ (format "(provide '%s)
;;; %s ends here
" feature-name file-name))
    ))

(defun debase-generate (bus service path interface class-name)
  "Generate and insert classes for a D-Bus interface."
  (interactive (let ((bus-service-path-interface (debase--complete)))
                 (append bus-service-path-interface (list (read-string "Class name: " (debase--interface->name (car (last bus-service-path-interface))))))))

  (with-output-to-temp-buffer (format "*debase %s*" interface)
    (princ (debase--generate
            class-name
            (concat class-name ".el")
            class-name
            (debase--interface (dbus-introspect-xml bus service path) interface)))))


(provide 'debase-gen)
;;; debase-gen.el ends here
